import { describe, it, expect, beforeEach } from "vitest";
import {
  GameScene,
  GameAction,
  AttackKind,
  EnemyWeaponKind,
  ENEMY_SHIELD_MAX,
  getInitialGameState,
  updateState,
  createEnemy,
  enemyAttack
} from "@/gameLogic/gameLogic.js";

// Generated by Claude Sonnet 4.6 Thinking, reviewed manually
describe("createEnemy", () => {
  const makeCounter = (start = 0) => () => ++start;

  it("should set initial shield to ENEMY_SHIELD_MAX", () => {
    const enemy = createEnemy(makeCounter(), 0, EnemyWeaponKind.DAGGER);
    expect(enemy.shield).toBe(ENEMY_SHIELD_MAX);
  });

  it("should set defeated to false", () => {
    const enemy = createEnemy(makeCounter(), 0, EnemyWeaponKind.DAGGER);
    expect(enemy.defeated).toBe(false);
  });

  it("should set level from argument", () => {
    const enemy = createEnemy(makeCounter(), 5, EnemyWeaponKind.DAGGER);
    expect(enemy.level).toBe(5);
  });

  it("should get enemyNum by calling incrementAndGetEnemyNum", () => {
    const counter = makeCounter(3);
    const enemy = createEnemy(counter, 0, EnemyWeaponKind.DAGGER);
    expect(enemy.enemyNum).toBe(4);
  });

  it("should call incrementAndGetEnemyNum exactly once", () => {
    let callCount = 0;
    const counter = () => {
      callCount++;
      return callCount;
    };
    createEnemy(counter, 0, EnemyWeaponKind.DAGGER);
    expect(callCount).toBe(1);
  });

  // Simplified from Sonnet 4.6 Thinking version
  describe("should initialize weapon with correct kind", () => {
    it.each([
      EnemyWeaponKind.DAGGER,
      EnemyWeaponKind.STICK,
      EnemyWeaponKind.SPEAR
    ])("kind: $kind", (kind) => {
      const enemy = createEnemy(makeCounter(), 0, kind);
      expect(enemy.weapon.kind).toBe(kind);
    });
  });
});

// Generated by Claude Sonnet 4.6 Thinking, reviewed manually
describe("enemyAttack", () => {
  const makeWeapon = (baseDamage, name = "dagger") => ({
    baseDamage,
    bonusDamageMin: 0,
    bonusDamageMax: 0,
    name
  });

  const makeState = ({ playerShield = 150, enemies = [] } = {}) => ({
    player: { shield: playerShield, defeated: false },
    enemies,
    messages: [],
    enemiesDefeated: 0,
    gameScene: GameScene.BATTLE_BASE
  });

  it("should reduce player shield by enemy's baseDamage", () => {
    const state = makeState({
      enemies: [{ enemyNum: 1, weapon: makeWeapon(10) }]
    });
    enemyAttack(state);
    expect(state.player.shield).toBe(140);
  });

  it("should push an attack message for the enemy", () => {
    const state = makeState({
      enemies: [{ enemyNum: 1, weapon: makeWeapon(10, "dagger") }]
    });
    enemyAttack(state);
    expect(state.messages).toContain("Enemy 1 attacks with its dagger for 10 damage!");
  });

  it("should apply damage from all enemies when player survives", () => {
    const state = makeState({
      playerShield: 150,
      enemies: [
        { enemyNum: 1, weapon: makeWeapon(10) },
        { enemyNum: 2, weapon: makeWeapon(5) }
      ]
    });
    enemyAttack(state);
    expect(state.player.shield).toBe(135);
  });

  it("should stop after the enemy that defeats the player", () => {
    const state = makeState({
      playerShield: 5,
      enemies: [
        { enemyNum: 1, weapon: makeWeapon(10, "dagger") },
        { enemyNum: 2, weapon: makeWeapon(10, "stick") }
      ]
    });
    enemyAttack(state);
    const hasEnemy2Message = state.messages.some(m => m.includes("Enemy 2 attacks"));
    expect(hasEnemy2Message).toBe(false);
  });

  it("should set gameScene to MENU_SCENE when player is defeated", () => {
    const state = makeState({
      playerShield: 1,
      enemies: [{ enemyNum: 1, weapon: makeWeapon(10) }]
    });
    enemyAttack(state);
    expect(state.player.defeated).toBe(true);
    expect(state.gameScene).toBe(GameScene.MENU_SCENE);
  });

  it("should push game over messages when player is defeated", () => {
    const state = makeState({
      playerShield: 1,
      enemies: [{ enemyNum: 1, weapon: makeWeapon(10) }]
    });
    state.enemiesDefeated = 3;
    enemyAttack(state);
    expect(state.messages).toContain("Player defeated after winning 3 battles! Game Over.");
    expect(state.messages).toContain("Click Restart to start a new game.");
  });
});

describe("State Transitions and Scene Flow", () => {
  let state;

  beforeEach(() => {
    // TODO: Better system for resetting state.
    state = {
      ...getInitialGameState(),
      gameScene: GameScene.MENU_SCENE,
      messages: []
    };
  });

  // Generated by Claude Sonnet 4.5, reviewed manually
  describe("Valid Scene Transitions", () => {
    it("should transition from MENU_SCENE to BATTLE_BASE on BATTLE action", () => {
      const newState = updateState(state, { type: GameAction.BATTLE });
      expect(newState.gameScene).toBe(GameScene.BATTLE_BASE);
    });

    it("should transition from BATTLE_BASE to BATTLE_SELECT_ATTACK on ATTACK action", () => {
      state.gameScene = GameScene.BATTLE_BASE;

      const newState = updateState(state, { type: GameAction.ATTACK });
      expect(newState.gameScene).toBe(GameScene.BATTLE_SELECT_ATTACK);
    });

    it("should transition from BATTLE_SELECT_ATTACK to BATTLE_SELECT_ENEMY on SELECT_ATTACK_KIND", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ATTACK;

      const newState = updateState(state, { type: GameAction.SELECT_ATTACK_KIND, attackKind: AttackKind.SWORD_SLASH });
      expect(newState.gameScene).toBe(GameScene.BATTLE_SELECT_ENEMY);
      expect(newState.attackKind).toBe(AttackKind.SWORD_SLASH);
    });

    it("should transition from BATTLE_SELECT_ENEMY back to BATTLE_BASE after SELECT_ENEMY", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ENEMY;
      state.attackKind = AttackKind.SWORD_SLASH;
      state.enemies = [
        { shield: 20, defeated: false, enemyNum: 1, level: 0, weapon: { baseDamage: 2, bonusDamageMin: 1, bonusDamageMax: 2 } },
        { shield: 20, defeated: false, enemyNum: 2, level: 0, weapon: { baseDamage: 2, bonusDamageMin: 1, bonusDamageMax: 2 } }
      ];

      const newState = updateState(state, { type: GameAction.SELECT_ENEMY, attackedEnemyIndex: 0 });
      expect(newState.gameScene).toBe(GameScene.BATTLE_BASE);
      expect(newState.attackKind).toBe(null);
    });

    it("should transition from BATTLE_SELECT_ATTACK to BATTLE_BASE on CANCEL_ATTACK", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ATTACK;

      const newState = updateState(state, { type: GameAction.CANCEL_ATTACK });
      expect(newState.gameScene).toBe(GameScene.BATTLE_BASE);
    });

    it("should transition from BATTLE_SELECT_ENEMY to BATTLE_BASE on CANCEL_ATTACK", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ENEMY;
      state.attackKind = AttackKind.SWORD_SLASH;

      const newState = updateState(state, { type: GameAction.CANCEL_ATTACK });
      expect(newState.gameScene).toBe(GameScene.BATTLE_BASE);
      expect(newState.attackKind).toBe(null);
    });

    it("should stay in MENU_SCENE after RESTART action", () => {
      state.gameScene = GameScene.MENU_SCENE;

      const newState = updateState(state, { type: GameAction.RESTART });
      expect(newState.gameScene).toBe(GameScene.MENU_SCENE);
    });

    // TODO: I'd like to mock `attack` so that we're guaranteed the enemy
    // is defeated even if we change/remove how power slash works
    it("should transition from BATTLE_BASE to MENU_SCENE when all enemies defeated", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ENEMY;
      state.attackKind = AttackKind.POWER_SLASH;
      state.enemies = [
        { shield: 1, defeated: false, enemyNum: 1, level: 0, weapon: { baseDamage: 2, bonusDamageMin: 0, bonusDamageMax: 0, kind: "DAGGER" } }
      ];

      const newState = updateState(state, { type: GameAction.SELECT_ENEMY, attackedEnemyIndex: 0 });
      expect(newState.gameScene).toBe(GameScene.MENU_SCENE);
      expect(newState.enemies.length).toBe(0);
    });

    // TODO: Same thing here, ideally we wouldn't rely on the attack logic
    // to cause the player to be defeated.
    it("should transition from BATTLE to MENU_SCENE when player defeated", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ENEMY;
      state.attackKind = AttackKind.SWORD_SLASH;
      state.player.shield = 1;
      state.enemies = [
        { shield: 20, defeated: false, enemyNum: 1, level: 0, weapon: { baseDamage: 50, bonusDamageMin: 0, bonusDamageMax: 0 } }
      ];

      const newState = updateState(state, { type: GameAction.SELECT_ENEMY, attackedEnemyIndex: 0 });
      expect(newState.gameScene).toBe(GameScene.MENU_SCENE);
      expect(newState.player.defeated).toBe(true);
    });
  });

  // Generated by Claude Sonnet 4.5, refactored with help from AI inline completions
  describe("invalid scene transitions", () => {
    const invalidSceneTransitions = [
      { from: GameScene.BATTLE_BASE, action: { type: GameAction.BATTLE } },
      { from: GameScene.MENU_SCENE, action: { type: GameAction.ATTACK } },
      { from: GameScene.BATTLE_BASE, action: { type: GameAction.SELECT_ATTACK_KIND, attackKind: AttackKind.SWORD_SLASH } },
      { from: GameScene.BATTLE_BASE, action: { type: GameAction.SELECT_ENEMY, attackedEnemyIndex: 0 } },
      { from: GameScene.BATTLE_BASE, action: { type: GameAction.RESTART } }
    ];

    invalidSceneTransitions.forEach(({ from, action }) => {
      it(`should throw error when ${action.type} action called from ${from}`, () => {
        state.gameScene = from;
        // store the initial state
        const { messages: messagesBefore, ...restBefore } = structuredClone(state);

        // run the update
        const newState = updateState(state, action);

        // destructure the updated state
        const { messages: messagesAfter, ...restAfter } = newState;

        expect(messagesAfter.length - messagesBefore.length).toBe(1);
        expect(messagesAfter[messagesAfter.length - 1]).toContain("not allowed from Scene");
        expect(restBefore).toEqual(restAfter);
      });
    });
  });

  // Generated by Claude Sonnet 4.5, refactored with help from AI inline completions
  describe("attackKind validation when attackKind must be null", () => {
    const scenesWithNullAttackKind = [
      { scene: GameScene.MENU_SCENE, action: { type: GameAction.RESTART } },
      { scene: GameScene.BATTLE_BASE, action: { type: GameAction.ATTACK } },
      { scene: GameScene.BATTLE_SELECT_ATTACK, action: { type: GameAction.SELECT_ATTACK_KIND, attackKind: AttackKind.SWORD_SLASH } }
    ];

    scenesWithNullAttackKind.forEach(({ scene, action }) => {
      it(`should have attackKind as null in ${scene}`, () => {
        state.gameScene = scene;
        state.attackKind = null;

        const newState = updateState(state, action);
        expect(newState.messages.some(m => m.includes("attackKind is not null in") || m.includes("attackKind is null in"))).toBe(false);
      });
    });

    // Repeat above check but set state.attackKind to a non-null value and
    // check that an error is recorded.
    scenesWithNullAttackKind.forEach(({ scene, action }) => {
      it(`should throw error if attackKind is not null in ${scene}`, () => {
        state.gameScene = scene;
        state.attackKind = AttackKind.SWORD_SLASH;

        // store the initial state
        const { messages: messagesBefore, ...restBefore } = structuredClone(state);

        const newState = updateState(state, action);

        // destructure the updated state
        const { messages: messagesAfter, ...restAfter } = newState;

        expect(messagesAfter.length - messagesBefore.length).toBe(1);
        expect(messagesAfter[messagesAfter.length - 1]).toContain("attackKind is not null");
        expect(restBefore).toEqual(restAfter);
      });
    });
  });

  // Generated by Claude Sonnet 4.5, reviewed manually
  describe("attackKind validation for BATTLE_SELECT_ENEMY", () => {
    it("should throw error if attackKind is null in BATTLE_SELECT_ENEMY", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ENEMY;
      state.attackKind = null;

      // store the initial state
      const { messages: messagesBefore, ...restBefore } = structuredClone(state);

      const newState = updateState(state, { type: GameAction.SELECT_ENEMY, attackedEnemyIndex: 0 });

      // destructure the updated state
      const { messages: messagesAfter, ...restAfter } = newState;

      expect(messagesAfter.length - messagesBefore.length).toBe(1);
      expect(messagesAfter[messagesAfter.length - 1]).toContain("attackKind is null");
      expect(restBefore).toEqual(restAfter);
    });

    it("should have valid attackKind in BATTLE_SELECT_ENEMY after selection", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ATTACK;

      const newState = updateState(state, { type: GameAction.SELECT_ATTACK_KIND, attackKind: AttackKind.POWER_SLASH });

      expect(newState.attackKind).toBe(AttackKind.POWER_SLASH);
      expect(newState.gameScene).toBe(GameScene.BATTLE_SELECT_ENEMY);
    });
  });
});
