import { describe, it, expect, beforeEach } from "vitest";
import {
  GameScene,
  GameAction,
  AttackKind,
  initGame,
  updateState
} from "@/gameLogic/gameLogic.js";

describe("State Transitions and Scene Flow", () => {
  let state;

  beforeEach(() => {
    state = {
      gameScene: GameScene.MENU_SCENE,
      messages: []
    };
    initGame(state);
  });

  // Generated by Claude Sonnet 4.5, reviewed manually
  describe("Valid Scene Transitions", () => {
    it("should transition from MENU_SCENE to BATTLE_BASE on BATTLE action", () => {
      updateState({ action: GameAction.BATTLE, state, options: {} });
      expect(state.gameScene).toBe(GameScene.BATTLE_BASE);
    });

    it("should transition from BATTLE_BASE to BATTLE_SELECT_ATTACK on ATTACK action", () => {
      state.gameScene = GameScene.BATTLE_BASE;

      updateState({ action: GameAction.ATTACK, state, options: {} });
      expect(state.gameScene).toBe(GameScene.BATTLE_SELECT_ATTACK);
    });

    it("should transition from BATTLE_SELECT_ATTACK to BATTLE_SELECT_ENEMY on SELECT_ATTACK_KIND", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ATTACK;

      updateState({
        action: GameAction.SELECT_ATTACK_KIND,
        state,
        options: { attackKind: AttackKind.SWORD_SLASH }
      });
      expect(state.gameScene).toBe(GameScene.BATTLE_SELECT_ENEMY);
      expect(state.attackKind).toBe(AttackKind.SWORD_SLASH);
    });

    it("should transition from BATTLE_SELECT_ENEMY back to BATTLE_BASE after SELECT_ENEMY", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ENEMY;
      state.attackKind = AttackKind.SWORD_SLASH;
      state.enemies = [
        { shield: 20, defeated: false, enemyNum: 1, level: 0, weapon: { baseDamage: 2, bonusDamageMin: 1, bonusDamageMax: 2 } },
        { shield: 20, defeated: false, enemyNum: 2, level: 0, weapon: { baseDamage: 2, bonusDamageMin: 1, bonusDamageMax: 2 } }
      ];

      updateState({
        action: GameAction.SELECT_ENEMY,
        state,
        options: { attackedEnemyIndex: 0 }
      });
      expect(state.gameScene).toBe(GameScene.BATTLE_BASE);
      expect(state.attackKind).toBe(null);
    });

    it("should transition from BATTLE_SELECT_ATTACK to BATTLE_BASE on CANCEL_ATTACK", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ATTACK;

      updateState({ action: GameAction.CANCEL_ATTACK, state, options: {} });
      expect(state.gameScene).toBe(GameScene.BATTLE_BASE);
    });

    it("should transition from BATTLE_SELECT_ENEMY to BATTLE_BASE on CANCEL_ATTACK", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ENEMY;
      state.attackKind = AttackKind.SWORD_SLASH;

      updateState({ action: GameAction.CANCEL_ATTACK, state, options: {} });
      expect(state.gameScene).toBe(GameScene.BATTLE_BASE);
      expect(state.attackKind).toBe(null);
    });

    it("should stay in MENU_SCENE after RESTART action", () => {
      state.gameScene = GameScene.MENU_SCENE;

      updateState({ action: GameAction.RESTART, state, options: {} });
      expect(state.gameScene).toBe(GameScene.MENU_SCENE);
    });

    // TODO: I'd like to mock `attack` so that we're guaranteed the enemy
    // is defeated even if we change/remove how power slash works
    it("should transition from BATTLE_BASE to MENU_SCENE when all enemies defeated", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ENEMY;
      state.attackKind = AttackKind.POWER_SLASH;
      state.enemies = [
        { shield: 1, defeated: false, enemyNum: 1, level: 0, weapon: { baseDamage: 2, bonusDamageMin: 0, bonusDamageMax: 0, kind: "DAGGER" } }
      ];

      updateState({
        action: GameAction.SELECT_ENEMY,
        state,
        options: { attackedEnemyIndex: 0 }
      });
      expect(state.gameScene).toBe(GameScene.MENU_SCENE);
      expect(state.enemies.length).toBe(0);
    });

    // TODO: Same thing here, ideally we wouldn't rely on the attack logic
    // to cause the player to be defeated.
    it("should transition from BATTLE to MENU_SCENE when player defeated", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ENEMY;
      state.attackKind = AttackKind.SWORD_SLASH;
      state.player.shield = 1;
      state.enemies = [
        { shield: 20, defeated: false, enemyNum: 1, level: 0, weapon: { baseDamage: 50, bonusDamageMin: 0, bonusDamageMax: 0 } }
      ];

      updateState({
        action: GameAction.SELECT_ENEMY,
        state,
        options: { attackedEnemyIndex: 0 }
      });
      expect(state.gameScene).toBe(GameScene.MENU_SCENE);
      expect(state.player.defeated).toBe(true);
    });
  });

  // Generated by Claude Sonnet 4.5, refactored with help from AI inline completions
  describe("invalid scene transitions", () => {
    const invalidSceneTransitions = [
      { from: GameScene.BATTLE_BASE, action: GameAction.BATTLE, options: {} },
      { from: GameScene.MENU_SCENE, action: GameAction.ATTACK, options: {} },
      { from: GameScene.BATTLE_BASE, action: GameAction.SELECT_ATTACK_KIND, options: { attackKind: AttackKind.SWORD_SLASH } },
      { from: GameScene.BATTLE_BASE, action: GameAction.SELECT_ENEMY, options: { attackedEnemyIndex: 0 } },
      { from: GameScene.BATTLE_BASE, action: GameAction.RESTART, options: {} }
    ];

    invalidSceneTransitions.forEach(({ from, action, options }) => {
      it(`should throw error when ${action} action called from ${from}`, () => {
        state.gameScene = from;

        expect(() => {
          updateState({ action, state, options });
        }).toThrow(/not allowed from Scene/);
      });
    });
  });

  // Generated by Claude Sonnet 4.5, refactored with help from AI inline completions
  describe("attackKind validation when attackKind must be null", () => {
    const scenesWithNullAttackKind = [
      { scene: GameScene.MENU_SCENE, action: GameAction.RESTART, options: {} },
      { scene: GameScene.BATTLE_BASE, action: GameAction.ATTACK, options: {} },
      { scene: GameScene.BATTLE_SELECT_ATTACK, action: GameAction.SELECT_ATTACK_KIND, options: { attackKind: AttackKind.SWORD_SLASH } }
    ];

    scenesWithNullAttackKind.forEach(({ scene, action, options }) => {
      it(`should have attackKind as null in ${scene}`, () => {
        state.gameScene = scene;
        state.attackKind = null;

        expect(() => {
          updateState({ action, state, options });
        }).not.toThrow();
      });
    });

    // Repeat above check but set state.attackKind to a non-null value and
    // check that an error is thrown.
    scenesWithNullAttackKind.forEach(({ scene, action, options }) => {
      it(`should throw error if attackKind is not null in ${scene}`, () => {
        state.gameScene = scene;
        state.attackKind = AttackKind.SWORD_SLASH;

        expect(() => {
          updateState({ action, state, options });
        }).toThrow(/attackKind is not null/);
      });
    });
  });

  // Generated by Claude Sonnet 4.5, reviewed manually
  describe("attackKind validation for BATTLE_SELECT_ENEMY", () => {
    it("should throw error if attackKind is null in BATTLE_SELECT_ENEMY", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ENEMY;
      state.attackKind = null;

      expect(() => {
        updateState({ action: GameAction.SELECT_ENEMY, state, options: { attackedEnemyIndex: 0 } });
      }).toThrow(/attackKind is null/);
    });

    it("should have valid attackKind in BATTLE_SELECT_ENEMY after selection", () => {
      state.gameScene = GameScene.BATTLE_SELECT_ATTACK;

      updateState({
        action: GameAction.SELECT_ATTACK_KIND,
        state,
        options: { attackKind: AttackKind.POWER_SLASH }
      });

      expect(state.attackKind).toBe(AttackKind.POWER_SLASH);
      expect(state.gameScene).toBe(GameScene.BATTLE_SELECT_ENEMY);
    });
  });
});
